spring:
  application:
    name: DAMPF
  servlet:
    multipart:
      max-file-size: "100MB"
      max-request-size: "100MB"
  jpa:
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
    open-in-view: true
    hibernate:
      ddl-auto: "update"
    database-platform: "org.hibernate.dialect.MariaDBDialect"
  datasource:
    driver-class-name: "org.mariadb.jdbc.Driver"
    username: "root"
    password: "root"
    url: "jdbc:mariadb://localhost:3306/sol"